### ISSUE TITLE
Is there a way to use Skrifa without making an account on skrifa.xyz?

### ISSUE THREAD

**Issue by Weej1** [Skrifa/Skrifa#1]
Hi there! 
found this app about 2 weeks ago and was wondering ... well what its says in title I guess :)

**Comment by HyuchiaDiego** [comment]
Hi! currently that's not possible but will definitively be a feature of the next release. It's currently like that so that people don't have to save their key and backup it themselves (many could lost it) but I know many people would feel safer knowing that even thought the key is encrypted their key is never online. 

Is that the reason you would like to skip creating an account or do you have another one?

**Comment by Hyuchia** [comment]
Hi! just wanted to update on this, with the code that's in master right now, using PGP keys is now completely possible :) [Skrifa v0.2.6](https://github.com/Skrifa/Skrifa/projects/1) will be the release with this feature incorporated, I still don't have a release ETA since I'm still adding some features and fixing some bugs but it will be soon enough. This issue will be closed once it gets officially released.

**Comment by Weej1** [comment]
Thanks so much, I completely forgot about this! I've honestly been searching for a way where I can grab snippets from the browser or set a global key to call something like Skrifa up and kinda use it like a sticky note app (imagine tomboy/gnote). 

One of the issues I faced was constantly putting in the username/pass everytime called Skrifa from my global hotkey (I don't think this is your fault maybe its just how I setup the global hotkey).

So I kinda got frustrated and gave up :no_mouth: 

Also because I didn't think you'd be interested in hearing all my ideas for Skrifa when it seemed drastically different from what you were trying to achieve.

**Comment by Hyuchia** [comment]
Ah well, while this will remove the need for a Skrifa account, notes will still be encrypted and thus you'll still need to type your decryption password, if you don't want them to be encrypted then you can use the  [Chrome extension](https://chrome.google.com/webstore/detail/skrifa/pfdkhjakblfafmapniifbpkjblgolipd) which provides almost the same experience but with no encryption and thus no need to enter any password :)

**Comment by Hyuchia** [comment]
Hey there, as you may know already, the latest Skrifa v0.2.6 was published a few weeks ago with the possibility of using your own PGP key without the need of an Skrifa account like I said earlier. Along with this update, a new app was also released, Skrifa Lite may suit your needs best. It does not features encryption and thus will not need you to enter any passphrase. You can check them out on the website! https://skrifa.xyz/

**Comment by Weej1** [comment]
This is awesome! I saw the lite version and didn't get what it meant - but this is exactly the kind of thing I can recommend to others. Personally after reading your posts I understood WHY you used the login system and I've been the Normal version of Skrifa since. But awesome that you made this version too! 

Made another post filled with my ideas - hopefully they're implementable! :)
